resources:
  - name: ci_parallel_gitRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: https://github.com/Gow17
      branches:
        include: main|^jfrog/.*
pipelines:
  - name: ci_parallel
    configuration:
      nodePool: parallel
      environmentVariables:
        readOnly:
          TYPE: "step"
          DRYRUN: "true"
    steps:
      - name: parallel
        type: Matrix
        stepMode: Bash
        configuration:
          multiNode: true
          inputResources:
            - name: ci_parallel_gitRepo
          integrations:
            - name: ci_parallel_envs
        stepletMultipliers:
          environmentVariables:
            - PARALLEL_NO: 1
            - PARALLEL_NO: 2
            - PARALLEL_NO: 3
            - PARALLEL_NO: 4
            - PARALLEL_NO: 5
        execution:
          onStart:
            - update_commit_status ci_parallel_gitRepo # Status: "processing"
          onExecute:
            - update_commit_status ci_parallel_gitRepo # Status: "processing"
            - pushd ${res_ci_parallel_gitRepo_resourcePath}
            - ./topi
            - popd
          onFailure:
            - update_commit_status ci_parallel_gitRepo # Status: "failure"
          onSuccess:
            - update_commit_status ci_parallel_gitRepo # Status: "success"
